/*
* Copyright (C) 2024 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
import { BuilderNameConstants, buildRouterModel, RouterModule, } from 'leafrouter';

@Builder
export function harBuilder(value: object) {
  NavDestination() {
    B2()
  }
  .title('B2Page')
  .onBackPressed(() => {
    RouterModule.pop();
    return true;
  })
}

@Component
struct B2{
  aboutToAppear(): void {
    let p = RouterModule.router.getParamByIndex(0) as Map<string, Object>;
    console.log("b2 about to appera");
  }
  build() {
    Column() {
      Button("pop", { stateEffect: true, type: ButtonType.Capsule })
        .width('80%')
        .height(40)
        .margin(20)
        .onClick(() => {
          RouterModule.pop();
        })
      Button("back to b1", { stateEffect: true, type: ButtonType.Capsule })
        .width('80%')
        .height(40)
        .margin(20)
        .onClick(() => {
          RouterModule.popToName( BuilderNameConstants.HARB_B1)
        })
      Button("back to a1", { stateEffect: true, type: ButtonType.Capsule })
        .width('80%')
        .height(40)
        .margin(20)
        .onClick(() => {
          RouterModule.popToName(BuilderNameConstants.HARA_A1)
        })
    }
    .width('100%')
    .height('100%')
  }
}

const builderName = BuilderNameConstants.HARB_B2;
let builder: WrappedBuilder<[object]> = wrapBuilder(harBuilder);
RouterModule.registerBuilder(builderName, builder);
